version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - /root/azazel/Bolg/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: xxxxxx
      POSTGRES_USER: xxxxxx
      POSTGRES_PASSWORD: xxxxxx
    ports:
      - "5432:5432"
    volumes:
      - /root/azazel/data/:/var/lib/postgresql/data/

  web:
    build: .
    command: uwsgi --ini blog/uwsgi.ini
    volumes:
      - /root/azazel/Blog/blog:/blog
    ports:
      - "8000:8000"
    links:
      - db
