# Generated by Django 2.0.4 on 2018-04-09 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
