# Generated by Django 2.0.4 on 2018-05-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180503_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='visits_num',
            field=models.IntegerField(default=-1),
        ),
    ]
