# Generated by Django 2.0.4 on 2018-05-21 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planning_time',
            field=models.DateField(default=datetime.datetime(2018, 5, 21, 19, 44, 30, 397600)),
        ),
    ]
