# Generated by Django 2.0.4 on 2018-05-21 19:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20180521_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='planning_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
