# Generated by Django 2.0.4 on 2018-05-25 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_plan_emergency_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='emergency_level',
            field=models.IntegerField(choices=[(0, '有空再做'), (1, '正常处理'), (2, '优先处理'), (3, '十万火急')], default=1),
        ),
    ]
